spring:
  profiles:
    active:
      - dev

---

spring:
  profiles: dev
  application:
    name: microservice-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka/

---

spring:
  profiles: test
  application:
    name: microservice-config-client

eureka:
  client:
    service-url:
      defaultZone: http://eureka02:7002/eureka/
